version: "3.1"
services:
  user_db_host:
    image: postgres
    restart: on-failure
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_pass
      POSTGRES_DB: user_db
    volumes: 
      - ./userdb:/var/lib/postgresql/data
      - ./db/userInit.sql:/docker-entrypoint-initdb.d/userInit.sql
      
  user_service:
    restart: on-failure
    build: 
      context: ./users-service
      dockerfile: Dockerfile
    environment:
      - POSTGRES_URI=postgresql://postgres_user:postgres_pass@user_db_host:5432/user_db
    ports:
      - 3100:3100
    depends_on:
      - user_db_host
    command: npm run start

volumes:
  userdb:
    driver: local
