version: "3.1"
services:
  mongodb:
    image: mongo
    restart: on-failure
    ports:
      - 27017:27017
      
  product-service:
    restart: on-failure
    build: 
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3200:3200
    depends_on:
      - mongodb
    command: npm run start