version: "3.1"
services:
  product_db_host:
    image: mongo
    restart: on-failure
    ports:
      - 27017:27017
    networks:
      - cloud-services
      
  product_service:
    restart: on-failure
    build: 
      context: ./products-service
      dockerfile: Dockerfile
    ports:
      - 3200:3200
    depends_on:
      - product_db_host
    command: npm run start