version: "3.1"
services:
  mongodb:
    image: mongo
    restart: on-failure
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoUser
      MONGO_INITDB_ROOT_PASSWORD: mongoPass
    volumes: 
      - db:/data/db
      
  order-service:
    restart: on-failure
    build: 
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3200:3200
    depends_on:
      - mongodb
    command: npm run start

volumes:
  db:
