version: "3.1"
services:
  order_db_host:
    image: postgres
    restart: on-failure
    ports:
      - 5100:5432
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_pass
      POSTGRES_DB: order_db
    volumes: 
      - ./orderdb:/var/lib/postgresql/data
      - ./db/orderInit.sql:/docker-entrypoint-initdb.d/orderInit.sql
      
  order_service:
    restart: on-failure
    build: 
      context: ./orders-service
      dockerfile: Dockerfile
    environment:
      ORDER_SERVICE_PORT: 3300
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_pass
      POSTGRES_DB: order_db
      POSTGRES_PORT: 5432
      POSTGRES_HOST: order_db_host
      POSTGRES_URI: postgresql://postgres_user:postgres_pass@order_db_host:5432/order_db
    ports:
      - 3300:3300
    depends_on:
      - order_db_host
    command: npm run start

volumes:
  orderdb:
    driver: local
